### PR TITLE
Added my Information

### PR DESCRIPTION
**Pull request by kc1100**
Added my Information

### CODE REVIEW

**Comment by TANYA03GUPTA** [comment]
Hey @kc1100  did the Hacktoberfest website count this pr ?

**Comment by kc1100** [comment]
No this pr is excluded.

**Comment by TANYA03GUPTA** [comment]
@kc1100 Thanks for replying, thats bad . do u know one that is accepted in the official website ? I have been submiting PR's and almost all Repos got exculded . It would be great if we could help each other out.

**Comment by kc1100** [comment]
I've find these two links hope that helps 
1. https://github.com/topics/hacktoberfest
2. https://hacktoberfest-projects.vercel.app/

**Pull request merged**
